### ISSUE TITLE
Token validation error occurred during a pool request

### ISSUE THREAD

**Issue by b0gdaniy** [ethereum-optimism/ethereum-optimism.github.io#655]
While submitting a PR for the SMT token support on BASE mainnet: #642 
The validation of this PR [failed](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/7886893209/job/21778986640) with the description:
```
[ 'SMT' ]
 ELIFECYCLE  Command failed with exit code 1.
/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/generate.ts:40
      const logoext = logofiles[0].endsWith('png') ? 'png' : 'svg'
                                   ^

TypeError: Cannot read properties of undefined (reading 'endsWith')
    at <anonymous> (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/generate.ts:40:36)
    at Array.map (<anonymous>)
    at generate (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/generate.ts:33:6)
    at validate (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/src/validate.ts:330:[16](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/7886893209/job/21778986640?pr=642#step:10:17))
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Command.<anonymous> (/home/runner/work/ethereum-optimism.github.io/ethereum-optimism.github.io/bin/cli.ts:25:[21](https://github.com/ethereum-optimism/ethereum-optimism.github.io/actions/runs/7886893209/job/21778986640?pr=642#step:10:22))
```
Is this validation error related to the provided `.svg` image or something else? And how can this problem be solved?

@roberto-bayardo , @roninjin10 
Looking forward to your help 🙌

**Comment by b0gdaniy** [comment]
Needs to change picture name to `logo.svg`.
